before_install:
  - sudo apt-get -y -qq update
  - sudo apt-get -y -qq install curl make libgc-dev
  - git clone --depth=1 git://github.com/nddrylliog/rock.git 
  - (cd rock && make -s quick-rescue)
  - mkdir dummyprefix
  - export PREFIX=$PWD/dummyprefix
  - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
  - export PATH=$PATH:$PWD/rock/bin:$PWD/dummyprefix/bin
  - wget http://libsdl.org/release/SDL2-2.0.1.tar.gz -O - | tar xz
  - (cd SDL2-2.0.1 && ./configure --prefix=$PREFIX && make -j5 && make install)
  - wget http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz -O - | tar xz
  - (cd SDL2_image-2.0.0 && ./configure --prefix=$PREFIX && make -j5 && make install)
  - wget http://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz -O - | tar xz
  - (cd SDL2_mixer-2.0.0 && ./configure --prefix=$PREFIX && make -j5 && make install)

script:
  - export OOC_LIBS=$PWD
  - cd samples
  - mkdir -p travis
  - rock -v window.ooc -o=travis/window -I$PREFIX/include -L$PREFIX/lib
  - rock -v loadpng.ooc -o=travis/loadpng -I$PREFIX/include -L$PREFIX/lib
  - rock -v spinning.ooc -o=travis/spinning -I$PREFIX/include -L$PREFIX/lib
  - rock -v joystick.ooc -o=travis/fontrender -I$PREFIX/include -L$PREFIX/lib
  - rock -v controller.ooc -o=travis/fontrender -I$PREFIX/include -L$PREFIX/lib
  - rock -v playwav.ooc -o=travis/fontrender -I$PREFIX/include -L$PREFIX/lib
  - rock -v fontrender.ooc -o=travis/fontrender -I$PREFIX/include -L$PREFIX/lib
